### ISSUE TITLE
Fractional hour time zones

### ISSUE THREAD

**Issue by prichterich** [RP6conrad/ESP-GPS-Logger#14]
The web configuration interface should support fractional time zones. I'm currently at Lake George in South Australia (with a few dozen other speedsurfers), and the time zone is UTC +10:30. Western Australia also has a time zone that is UTC +8:45.
Currently, the box for time zone seems to allow only integers.

**Comment by RP6conrad** [comment]
I will change the timezone offset from hours -> minutes.

**Comment by prichterich** [comment]
Using a float is the easiest solution for programming, but it will certainly confuse many users. The same will be true for using minutes. Another disadvantage for both is that users can enter invalid values.

I would suggest to spend some extra time and present the allowed choices as a drop-down menu, similar to the way you can set the time zone in the GPS Speedreader preferences. This adds some coding overhead, but that is a one-time effort that users will benefit from forever.

**Comment by RP6conrad** [comment]
Will go that direction (drop down menu with all timezones). What about daylight saving, is that an issue in these partial timezones ?

**Comment by prichterich** [comment]
Of the time zones with fractional hour offsets, the only one I have seen lots of postings of is South Australia (+9:30). There is an entry in Speedreader's drop down that works for summer time (+10:30 Australia/LHI). There are a few other regions in Asia and the Pacific, and one in Oz (Eucla) that have fractional time zones, but I don't think speedsurfing is popular there, and some zones (like Australia / Eucla) do not use summer time. 
Theoretically, you could add an extra checkbox for summer time, or even try to determine automatically if it applies, but I think that's overkill.

**Comment by RP6conrad** [comment]
Timezone choice with drop down menu in now in latest SW 5.73.
