### ISSUE TITLE
Remove extra underscores in file names

### ISSUE THREAD

**Issue by prichterich** [RP6conrad/ESP-GPS-Logger#15]
Files downloaded through the web interface on MacOS all start with an underscore ('_', e.g. "_2301301325_Nina2.gpy") that should not be present. The underscore may result from the leading slash that is shown in the file name on the web page, and replaced by an underscore when downloading. It is possible that Windows simply ignores the leading slash, so that this is a macOS-specific problem.
The issue exists on different macOS versions (tested 10.14 and 11.7) and with different browsers (tested Safari and Firefox).

**Comment by Rolzzz** [comment]
> Files downloaded through the web interface on MacOS all start with an underscore ('_', e.g. "_2301301325_Nina2.gpy") that should not be present. The underscore may result from the leading slash that is shown in the file name on the web page, and replaced by an underscore when downloading. It is possible that Windows simply ignores the leading slash, so that this is a macOS-specific problem. The issue exists on different macOS versions (tested 10.14 and 11.7) and with different browsers (tested Safari and Firefox).

can confirm on windows I get _Rolz_2301291253.ubx on my file names when I save them.

**Comment by RP6conrad** [comment]
Just found the rootcause of the _ with downloading : lib fs.h returns file.name() with a leading / (for root dir ?). This is then changed to a underscore with downloading. will be fixed in the next update.

**Comment by RP6conrad** [comment]
Underscore bug is fixed in the latest SW 5.73.
