### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by prichterich** [RP6conrad/ESP-GPS-Logger#2]
I suggest to change the naming of the log files to include the date (preferably at the front, and in yyyy-mm-dd format), and possibly also the time (add <space or underscore>hhmm).
In theory, the date and time file stamps on the files could be used, but in practice, transferring the files with FTP time stamps the transferred files with the date and time of transfer, so the original dates and times are lost.

To prevent file names from getting very long, but to keep information about the units used, the MAC address can be shortened to the last 4 digits in the file names. The first 8 characters of the MAC address tend to be identical or almost identical for ESP units, so they add very little information.

**Comment by RP6conrad** [comment]
With WinSCP (FTP client for Windows), the correct date/time stamps are transferred, but maybe other FTP clients behave different.

Greetings, Jan.

Verzonden vanuit Mail voor Windows

Van: prichterich
Verzonden: zaterdag 14 mei 2022 15:46
Aan: RP6conrad/ESP-GPS-Logger
CC: Subscribed
Onderwerp: [RP6conrad/ESP-GPS-Logger] File naming (Issue #2)

I suggest to change the naming of the log files to include the date (preferably at the front, and in yyyy-mm-dd format), and possibly also the time (add hhmm).
In theory, the date and time file stamps on the files could be used, but in practice, transferring the files with FTP time stamps the transferred files with the date and time of transfer, so the original dates and times are lost.
To prevent file names from getting very long, but to keep information about the units used, the MAC address can be shortened to the last 4 digits in the file names. The first 8 characters of the MAC address tend to be identical or almost identical for ESP units, so they add very little information.

**Comment by prichterich** [comment]
I just double-checked, and FileZilla on macOS sets both creation and modification date of the file to the transfer date. FileZilla is also the only ftp program that seems to work (I've tried 3 or 4 others). Of the speedsurfers I know in the US and Australia, a lot are Mac users.

**Comment by jetsoftwind** [comment]
I use filezilla on windows and as long as the menu option - Transfer/"Preserve timeStamps of transferred files" is on then the modifed  date/times are correct the created time is the transfer time. On windows the shortcut key is Ctrl-U

**Comment by Rolzzz** [comment]
just bumping this one, I'm using new method of pulling down from internal web browser and file format when downloading is as follows

_Rolz_94B555C8DB1C_000.ubx
_Rolz_94B555C8DB1C_001.ubx
_Rolz_94B555C8DB1C_002.ubx

if I download and then delete from device it creates a new file that again starts from _Rolz_94B555C8DB1C_000.ubx
then if I try to save to my gps file location on my computer I get message file already exists.
if file name could include date that would be awesome. :)
