### ISSUE TITLE
GPY format documentation

### ISSUE THREAD

**Issue by ghost** [RP6conrad/ESP-GPS-Logger#32]
I can't find information on the .gpy format, is there a place with documentation on how to decode it ?

**Comment by RP6conrad** [comment]
More information here : https://github.com/prichterich/compactgnss/blob/main/README.md
Let me know if you need more information. 

Greetings, Jan.

Verzonden vanuit Mail voor Windows

Van: ciel-d-automne
Verzonden: dinsdag 16 juli 2024 19:19
Aan: RP6conrad/ESP-GPS-Logger
CC: Subscribed
Onderwerp: [RP6conrad/ESP-GPS-Logger] GPY format documentation (Issue #32)

I can't find information on the .gpy format, is there a place with documentation on how to decode it ?

**Comment by RP6conrad** [comment]
Is there an API for direct posting to the website ?
Greetings, Jan.

Op za 20 jul 2024 15:54 schreef ciel-d-automne ***@***.***>:
